### ISSUE TITLE
character.txtやcopyright.txtでの括弧のエスケープ

### ISSUE THREAD

**Issue by Zuntan03** [p1atdev/sd-danbooru-tags-upsampler#1]
character.txtやcopyright.txtで括弧がエスケープされていません。
AnimagineのキャラWildcardなどが受け入れられるように、( ) と \\( \\) を状況に合わせて置換してはいかがでしょうか。
https://huggingface.co/spaces/Linaqruf/animagine-xl/resolve/main/wildcard/character.txt

プロンプト入力欄
括弧エスケープ有り、Animagineなどのモデルの入力が括弧有り想定ですので。

Dart入力
括弧エスケープ無し？学習時が括弧なしなため？

Dart出力（画像生成）
括弧エスケープ有り、( ) のままですと 1.1倍のプロンプト強調となってしまうため。

character.txtやcopyright.txtの内容
そのままWildcardなどで利用することを想定するなら括弧エスケープ有り？
ただしWidlcardにいれるならcharacter_copyright.txtのようにキャラと作品をマッチさせたものが求められそうです。
どちらでも？

といったあたりで、プロンプト入力欄でAnimagineなどのキャラWildcardを含めた際に、エスケープ済み括弧が適切に入出力されると良さそうです。

**Comment by Zuntan03** [comment]
> プロンプト入力欄でAnimagineなどのキャラWildcardを含めた際に

としていましたが、そもそも Wildcard が未解決の状態でDartに渡されているようですかね？
もし可能でしたら Wildcard を解決した結果を Dart に渡せますと、簡単なWildcardとDartの組み合わせで、多様で充実したプロンプトを生成できそうです（が、スレッド違いですね）。

**Comment by p1atdev** [comment]
エスケープされた括弧に関する挙動を修正しました。

`Allow escaped brackets in input prompt.` が有効な場合 (デフォルト)、エスケープされた括弧でもタグを認識できるようになっています。

![image](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/60182057/fce7098d-2570-4a57-9f00-9f1060f9988b)

これに加えて、` Upsampling timing` を `After applying other prompt processings` にすることで、sd-dynamic-prompts の処理後(ワイルドカード等)にアップサンプルされるようになります。

![image](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/60182057/5de6a807-02fe-4a39-b918-1e5b7b573634)

下のスクリーンショットでは `{from side|from behind}` を指定し、 `from behind` が選ばれた後に `looking back` が補完されている様子です。
![image](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/60182057/5f1440a3-50b4-45d0-83d6-aa9f48b3085d)

また、`Escape brackets in upsampled tags.` が有効で、出力されるタグに括弧が含まれていた場合にその括弧をエスケープするようにも変更しました。
