### ISSUE TITLE
Classifier-Free Guidance hidden?

### ISSUE THREAD

**Issue by catboxanon** [p1atdev/sd-danbooru-tags-upsampler#17]
Is there a particular reason these controls are hidden currently?

https://github.com/p1atdev/sd-danbooru-tags-upsampler/blob/3673b242930df9454619c36188941fdef9569efc/scripts/dart_upsampler.py#L184-L202

**Comment by p1atdev** [comment]
Currently, I don't see any effect when CFG is enabled, so the options are hidden. A better negative prompt composition may exist, but I have not investigated it yet. 
I plan to enable it if future model improvements work with CFG effectively.
