### ISSUE TITLE
Generate ForeverとX/Y/Z Plotで「タグのアップサンプリング用シード値」の振る舞いが他の拡張と異なる

### ISSUE THREAD

**Issue by Zuntan03** [p1atdev/sd-danbooru-tags-upsampler#2]
タグのアップサンプリング用シード値が -1 でない値だと、Generate Forever でプロンプトが固定されてしまいます。
タグのアップサンプリング用シード値が -1 だと、X/Y/Z Plot での複数画像の生成時に異なるプロンプトになってしまいます。

Wildcard機能のように、タグのアップサンプリング用シード値に -1 指定すると Generate Forever でプロンプトが変化しつつ、X/Y/Z plotの併用で同じプロンプトで複数モデルの出力比較などができると良さそうです。

このような仕様であれば UI 上の seed_num_input 初期値は -1 で問題ないように思います。

**Comment by p1atdev** [comment]
dev ブランチでシードの処理を修正してみました。以下ではアップサンプルのシードは -1 ですが、すべて同じシードを使ってアップサンプルされているため、元のプロンプトが同じになる場合(縦)は同じプロンプトで画像生成されています。

![xyz_grid-0024-3823959799](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/60182057/9d4a3dce-4495-45f4-9e6e-812e1d77134f)

- 入力プロンプト
```
1girl, solo, cat ears
```
- アップサンプルシード: -1 
- X/Y 設定:
![image](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/60182057/20a30a5f-63d6-408a-b289-6d78659244c6)

おそらくこれが期待される動作だと思うので、問題なさそうであればマージしようと思います。

**Comment by Zuntan03** [comment]
対応ありがとうございます。

Generate Foreverでプロンプトが変わりつつ、X/Y/Z Plotでプロンプトが共通であることを確認いたしました。
![image](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/121656336/b819d714-5c42-42fa-8756-6d43a3a6b548)

**Comment by Zuntan03** [comment]
mainへのマージ時に各チケットがPlatさん側でCloseされる想定ですが、もしチケット作成者がCloseすることを期待されているようでしたらお知らせください。

**Comment by p1atdev** [comment]
マージ時にcloseする予定です
