### ISSUE TITLE
DTG support

### ISSUE THREAD

**Issue by p1atdev** [p1atdev/sd-danbooru-tags-upsampler#23]
Add support of
- https://huggingface.co/KBlueLeaf/DanTagGen-alpha
- https://huggingface.co/KBlueLeaf/DanTagGen-beta

**Comment by catboxanon** [comment]
FYI, the author plans to implement this themself according to the README.

> I'm implementing a gradio UI for this thing and other dev can utilize the API in it to make different app. I'm also planning to make sd-webui extension.

**Comment by catboxanon** [comment]
Available here now: https://github.com/KohakuBlueleaf/a1111-sd-webui-dtg

**Comment by Zyin055** [comment]
Is DanTagGen not just a copy paste of this extension?

**Comment by catboxanon** [comment]
It's certainly based on this repo but is far from a copy paste.
