### ISSUE TITLE
[要望]forgeに対応希望

### ISSUE THREAD

**Issue by taka0070** [p1atdev/sd-danbooru-tags-upsampler#3]
使ってみてすごく便利で凄い拡張なのでぜひ、forgeにも対応して欲しいです。

**Comment by p1atdev** [comment]
こちらでは Forge でも動作確認をしていますが、何かエラーが出ていて動かない状態でしょうか？

**Comment by taka0070** [comment]
エラーは一切出てこずにアコーディオンに記載されていないだけです。
インストはされています

**Comment by taka0070** [comment]
2024-02-24 09:10:53の更新で無事に動くようになりました。ありがとうございます
