### ISSUE TITLE
This extension won't appear when intalled

### ISSUE THREAD

**Issue by bbggkk** [p1atdev/sd-danbooru-tags-upsampler#9]
This extension won't appear when intalled,
A1111 SD  1.70 
how to solve?
![ddd](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/65471489/b76a7257-d7ca-43f4-bed4-f3546b8aa54e)
![ddd1](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/65471489/e897a054-1a7f-4b2f-92a3-5bdb9d3c7e3a)

**Comment by p1atdev** [comment]
Are any errors displayed on your terminal?

**Comment by bbggkk** [comment]
> Are any errors displayed on your terminal?

I am not so sure this error is the reason,for the generate has no problem.
![RJ9Q 8B8$VN31%~142VO%IX](https://github.com/p1atdev/sd-danbooru-tags-upsampler/assets/65471489/6303859b-d114-4364-a3fd-1fd745648d32)

**Comment by p1atdev** [comment]
It looks like tensorflow is borken that is required by other extension. 
So, try reinstalling tensorflow.

```bash
pip uninstall tensorflow
```

Then start the webui and reinstalling tensorflow should start with an extension that depends on it.

If the error was not solved, I recommend that you reset your python environment.

Refs: 
- https://stackoverflow.com/questions/77582620/tensorflow-pywrap-tf2-importerror-dll-load-failed
- https://discuss.tensorflow.org/t/dll-load-failed-error-when-importing-tensorflow-pywrap-tfe/16567

**Comment by bbggkk** [comment]
> It looks like tensorflow is borken that is required by other extension. So, try reinstalling tensorflow.
> 
> ```shell
> pip uninstall tensorflow
> ```
> 
> Then start the webui and reinstalling tensorflow should start with an extension that depends on it.
> 
> If the error was not solved, I recommend that you reset your python environment.
> 
> Refs:
> 
> * https://stackoverflow.com/questions/77582620/tensorflow-pywrap-tf2-importerror-dll-load-failed
> * https://discuss.tensorflow.org/t/dll-load-failed-error-when-importing-tensorflow-pywrap-tfe/16567

When update python to newest version,it shows,thanks for reply.
